language: node_js
branches:
  only:
  - master
  - develop
node_js:
- 8
script:
- yarn build
deploy:
- provider: gae
  keyfile: .travis/keys/client-secret-dev.json
  project: dev-drug-portal
  skip_cleanup: true
  on:
    branch: develop
- provider: gae
  keyfile: client-secret-prod.json
  project: drug-portal
  skip_cleanup: true
  on:
    branch: master

before_install:
  - echo $CLIENT_SECRET_DEV > .travis/keys/client-secret-dev.json
