language: node_js
branches:
  only:
  - master
  - develop
node_js:
- 8
script:
- yarn build
deploy:
- provider: gae
  keyfile: client-secret-dev.json
  project: dev-drug-portal
  skip_cleanup: true
  on:
    branch: develop
- provider: gae
  keyfile: client-secret-prod.json
  project: drug-portal
  skip_cleanup: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_d38d7a19446e_key -iv $encrypted_d38d7a19446e_iv
  -in .travis/keys/client-secret-prod.json.enc -out client-secret-prod.json -d
- openssl aes-256-cbc -K $encrypted_d38d7a19446e_key -iv $encrypted_d38d7a19446e_iv
  -in .travis/keys/client-secret-dev.json.enc -out client-secret-dev.json -d
