language: node_js
branches:
  only:
  - master
  - develop
  - feature/travis-ci
node_js:
- 8
script:
- yarn build
deploy:
- provider: gae
  keyfile: /tmp/client-secret-dev.json
  project: dev-drug-portal
  skip_cleanup: true
  on:
    branch: feature/travis-ci
- provider: gae
  keyfile: client-secret-prod.json
  project: drug-portal
  skip_cleanup: true
  on:
    branch: master

before_install:
  - echo $CLIENT_SECRET_DEV > /tmp/client-secret-dev.json
  - ls /tmp/client-secret-dev.json
