language: node_js
branches:
  only:
  - master
  - develop
node_js:
- 8

before_install:
- openssl aes-256-cbc -K $encrypted_d38d7a19446e_key -iv $encrypted_d38d7a19446e_iv
  -in .travis/keys/client-secret-prod.json.enc -out secrets/client-secret-prod.json
  -d
- openssl aes-256-cbc -K $encrypted_d38d7a19446e_key -iv $encrypted_d38d7a19446e_iv
  -in .travis/keys/client-secret-dev.json.enc -out secrets/client-secret-dev.json
  -d

script:
- npm run build

deploy:
- provider: gae
  keyfile: secrets/client-secret-dev.json
  project: dev-drug-portal
  on:
    branch: develop

- provider: gae
  keyfile: secrets/client-secret-prod.json
  project: drug-portal
  on:
    branch: master
